global_costmap:
  global_frame: map
  robot_base_frame: t265_pose_frame
  update_frequency: 1.0
  publish_frequency: 1.0
  inflation_radius: 0.5
  robot_radius: 0.1
  resolution: 0.05
  static_map: true
  rolling_window: false
