local_costmap:
  global_frame: t265_odom_frame
  robot_base_frame: t265_pose_frame
  update_frequency: 30.0
  publish_frequency: 30.0
  resolution: 0.05
  rolling_window: true
  width: 4.0
  height: 4.0
  track_unknown_space: false
  plugins:
    - { name: occupancy_map, type: "costmap_2d::StaticLayer" }
    - { name: "obstacle_layer", type: "costmap_2d::ObstacleLayer" }
    - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

  inflation_layer:
    cost_scaling_factor: 0.5
    inflation_radius: 0.25

  obstacle_layer:
    track_unknown_space: false
    observation_sources: points

    points:
      topic: /d400/depth/color/points
      max_obstacle_height: 2
      min_obstacle_height: 0.05
      clearing: true
      marking: true
      inf_is_valid: true
      data_type: PointCloud2
      raytrace_max_range: 2.0
      raytrace_min_range: 0.05
      obstacle_range: 2.0

  occupancy_map:
    map_topic: /occupancy
    track_unknown_space: false
