NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

GlobalPlanner: # For list of available parameters, see http://wiki.ros.org/global_planner
  allow_unknown: true # Specifies whether or not to allow the global planner to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.
  use_dijkstra: false # Specifies whether or not to use dijkstra's algorithm or A* for planning.
  neutral_cost: 66 # The cost that the planner assigns to cells with no information.
  lethal_cost: 253 # The cost that the planner assigns to cells with lethal obstacles.
  cost_factor: 0.5

DWAPlannerROS:
  max_vel_x: 5
  min_vel_x: 0
  max_vel_y: 5
  min_vel_y: 0

# footprint: [[0.80, 0.80], [0.80, -0.80], [-0.80, -0.80], [-0.80, 0.80]]
robot_radius: 0.25
obstacle_range: 2.5
raytrace_range: 3.0

global_costmap:
  transform_tolerance: 1000000000.000000
  global_frame: global_map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: false
  track_unknown_space: true
  plugins:
    - { name: static_map, type: "costmap_2d::StaticLayer"}
    - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

  inflation_layer:
    cost_scaling_factor: 10.0
    inflation_radius: 0.1

  static_map:
    map_topic: /map
    track_unknown_space: true

local_costmap:
  transform_tolerance: 1000000000.000000
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  width: 10
  height: 10
  resolution: 0.05
  rolling_window: true
  track_unknown_space: false
  plugins:
    # - { name: occupancy_map, type: "costmap_2d::StaticLayer"}
    - { name: "obstacle_layer", type: "costmap_2d::ObstacleLayer" }
    - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

  inflation_layer:
    cost_scaling_factor: 0.5
    inflation_radius: 0.25

  obstacle_layer:
    track_unknown_space: false
    observation_sources: points

    points:
      topic: /depth
      max_obstacle_height: 2
      min_obstacle_height: 0
      clearing: true
      marking: true
      inf_is_valid: true
      data_type: PointCloud2
      raytrace_max_range: 3.0
      raytrace_min_range: 0.05
      obstacle_range: 3.0

  occupancy_map:
    map_topic: /occupancy/map
    subscribe_to_updates: true
    track_unknown_space: false