# costmap_params.yaml

local_costmap:
  global_frame: map
  # robot_base_frame: d400_link
  update_frequency: 5.0
  publish_frequency: 5.0
  resolution: 0.05  # Adjust based on your occupancy grid resolution
  width: 100  # Width in cells
  height: 100  # Height in cells
  origin_x: 0.0  # Origin in meters
  origin_y: 0.0  # Origin in meters
  transform_tolerance: 0.5

  plugins:
    - { name: "voxel_layer", type: "costmap_2d::VoxelLayer" }
    - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

voxel_layer:
  # The topic to listen to for point cloud messages
  observation_sources: laser
  laser: {data_type: pointCloud2, clearing: true, marking: true, topic: /d400/depth/color/points, inf_is_valid: true}