NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

global_costmap:
  transform_tolerance: 1000000000.000000
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  plugins:
    - { name: static_map, type: "costmap_2d::StaticLayer"}
    # - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

  inflation_layer:
    cost_scaling_factor: 10.0
    inflation_radius: 0.15

  static_map:
    map_topic: /map
    subscribe_to_updates: true
    track_unknown_space: true

local_costmap:
  transform_tolerance: 1000000000.000000
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  width: 10
  height: 10
  resolution: 0.05
  rolling_window: true
  # footprint: [[0.80, 0.80], [0.80, -0.80], [-0.80, -0.80], [-0.80, 0.80]]
  robot_radius: 0.15

  plugins:
    - { name: occupancy_map, type: "costmap_2d::StaticLayer"}
    - { name: "obstacle_layer", type: "costmap_2d::ObstacleLayer" }
    - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

  inflation_layer:
    cost_scaling_factor: 1.0
    inflation_radius: 0.025

  obstacle_layer:
    track_unknown_space: true
    observation_sources: points

    points:
      topic: /depth
      max_obstacle_height: 2
      min_obstacle_height: 0
      clearing: true
      marking: true
      inf_is_valid: true
      data_type: PointCloud2
      raytrace_max_range: 3.0
      raytrace_min_range: 0.05
      obstacle_range: 3.0

  occupancy_map:
    map_topic: /map
    subscribe_to_updates: true
    track_unknown_space: true

# global_costmap:
#   global_frame: map
#   robot_base_frame: odom
#   update_frequency: 5.0
#   publish_frequency: 5.0
#   origin_x: 0
#   origin_y: 0
#   footprint_clearing_enabled: true

#   plugins:
#     - { name: static_map, type: "costmap_2d::StaticLayer"}
#     - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

#   inflation_layer:
#     cost_scaling_factor: 10.0
#     inflation_radius: 0.15

#   static_map:
#     # get static map occupancygrid from topic /occupancy
#     # map_topic: /occupancy
#     map_topic: /map
#     subscribe_to_updates: true
#     track_unknown_space: true

  # static_map from file


